services:
  database:
    image: postgres:18.1-alpine3.22
    container_name: daily_diet_database
    env_file: ../.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 8

  test-database:
    image: postgres:18.1-alpine3.22
    container_name: daily_diet_test_database
    env_file: ../.env.test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 8
