name: Automated Test

on: pull_request

jobs:
  vitest:
    name: Vitest Ubuntu
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.19.0"
      - run: docker compose -f infra/compose.yml up -d test-database --wait
      - run: npm ci
      - run: npm test
